# Generated by Django 5.0.1 on 2024-01-20 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='PythonQuestions',
        ),
    ]
