# Generated by Django 5.0.1 on 2024-01-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_questions_correct_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='correct_option',
            field=models.CharField(choices=[('0', 'Option 1'), ('1', 'Option 2'), ('2', 'Option 3'), ('3', 'Option 4')], max_length=1),
        ),
    ]
