# Generated by Django 5.0.1 on 2024-01-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_questions_correct_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='correct_option',
            field=models.CharField(choices=[('A', 'Option 1'), ('B', 'Option 2'), ('C', 'Option 3'), ('D', 'Option 4')], max_length=1),
        ),
    ]
